### ISSUE TITLE
Failed to compile ps shader

### ISSUE THREAD

**Issue by ibrokemypie** [Tinob/Ishiiruka#101]
Error whilke launching games, comes uip even with ubershaders off entirely. Arch linux x64, vega56, amdgpu-dc-next 
```Failed to compile ps shader: /extra/home/.local/share/ishiiruka/Dump/bad_ps_0000.txt
Debug info (X.Org, AMD VEGA10 (DRM 3.21.0 / 4.14.0-rc3-26c860d55796, LLVM 5.0.0), 4.5 (Core Profile) Mesa 17.2.5):
0:372(33): error: syntax error, unexpected ';', expecting $end```

**Comment by Tinob** [comment]
can you attach the shader?

**Comment by ibrokemypie** [comment]
there are about 150 of them that fail.Sent from Nylas Mail, the best free email app for work
          
            
            On Nov 20 2017, at 2:13 am, Tinob <notifications@github.com> wrote:
            
            
              can you attach the shader?

**Comment by Tinob** [comment]
3 or 4 will be enough

**Comment by Tinob** [comment]
is his still happening in the latest version?

**Comment by ibrokemypie** [comment]
Nope, all fixed, sorry I didnt get back to you!
