### ISSUE TITLE
Rumble causing frame drops

### ISSUE THREAD

**Issue by jasonpanosso** [Tinob/Ishiiruka#112]
Been having a weird issue with rumble while playing offline/online.
When playing with rumble on with any controller, huge frame drops happen that make the game basically unplayable. 
Have tested different adapters, different controllers, reinstalling drivers, etc.
PC components:
AMD - Ryzen 5 1600X 3.6GHz 6-Core Processor
MSI - B350M GAMING PRO Micro ATX AM4 Motherboard
EVGA - GeForce GTX 1050 Ti 4GB SC GAMING ACX 2.0 Video Card

Any help would be appreciated : )

**Comment by Tinob** [comment]
this happends onlyunder ishiiruka or with other games to? can you check your task manager to see what proccess get increased cpu usage when the issue is present?

**Comment by iamschleep** [comment]
Only Ishiiruka, and CPU is stable
