### ISSUE TITLE
Change saves directory to Dolphin's save directory

### ISSUE THREAD

**Issue by billywade** [Tinob/Ishiiruka#117]
I'm running on Linux, and I'm wondering if I can set the save game directory to the same folder on both vanilla and Ishiiruka. 

I figure trying to change the entire user directory will cause a lot of problems, but I'm hoping I can do it on either application for just the saves directory, or at worst do a quick and dirty symlink from the saves folders in Ishiiruka to Dolphin's, but I don't know if Ishiiruka will take a symlink. 

Any ideas? 

EDIT: I figured it out. And for posterity, you can use symlinks.

**Comment by Tinob** [comment]
thanks for sharing it
