### ISSUE TITLE
error: 'GFX_PREFER_GLES' is not a member of 'Config' 

### ISSUE THREAD

**Issue by 5schatten** [Tinob/Ishiiruka#122]
Well I had to deal with this problem while building the libretro port and I got the advice to ask if this could be fixed in upstream.

https://pastebin.com/mWXubwzV

https://github.com/libretro/Ishiiruka/issues/2

**Comment by Tinob** [comment]
should be fixed now

**Comment by 5schatten** [comment]
thx I will report again it once the lr core is synced to upstream

**Comment by 5schatten** [comment]
Still waiting for an update of the libretro-Ishiiruka core. Otherwise I can't test it under real conditions.

**Comment by 5schatten** [comment]
https://github.com/libretro/Ishiiruka/issues/2#issuecomment-503663507
