### ISSUE TITLE
Normal Maps inverted in DirectX 11, 12 and Vulkan

### ISSUE THREAD

**Issue by GlitchGamingX** [Tinob/Ishiiruka#129]
opengl uses a lower-left UV origin, but D3D and Vulkan are upper-right
the fix is to have the shader subtract the y component from 1.0. 

![image](https://user-images.githubusercontent.com/37849930/50543967-f1303d00-0bb4-11e9-9a87-89f761d5748b.png)

**Comment by Tinob** [comment]
can you give me example tetures to test the issue?

**Comment by GlitchGamingX** [comment]
Sure, I have added a G-Drive Link, The Textures are a part of the Metroid Prime Remastered Project. The areas of the game where this is very visible are the Chozo Ruins (Corridor right before hive mecha) and Parasite Queen Boss fight. 

ParasiteQueen OpenGL (Using DirectX-Normals) looks fine, and the way it should. 
![image](https://user-images.githubusercontent.com/37849930/50670992-06cea980-0f9d-11e9-8c8a-a452bf44f2cf.png)

ParasiteQueen DirectX11/12/Vulkan (Using DirectX-Normals) looks inverted, notice the lighting on the upper scales of the creature..
![image](https://user-images.githubusercontent.com/37849930/50671043-4eedcc00-0f9d-11e9-8bd8-a3a3aa81a4e0.png)

Google Drive Link Below:
https://drive.google.com/open?id=104pymhSm1r4VV2LvoQK75XoFz41-rbJ0

Also just as a heads up, if you are really interested in Joining the MPR Project do let me know! It would be great to have someone who knows the ins and outs of the Emulator really well.

Thanks for getting back to me!

**Comment by Tinob** [comment]
should be fixed in the last version
