### ISSUE TITLE
Distorted textures in Wind Waker on DX11

### ISSUE THREAD

**Issue by greasysock** [Tinob/Ishiiruka#13]
I've been noticing that textures that render farther away appear to render at a much lower resolution than what opengl is. DX11 is running the game a lot more smoothly than opengl is though. I've turned off and on asynchronous textures, predictive fifo, and other options, and it seems to have no impact. Turning off scaled EFB copy makes things much worse.

DX11:
![gzle01-1](https://cloud.githubusercontent.com/assets/3253689/9499246/4ece6810-4bec-11e5-8ac3-e7d858653ecd.png)
OpenGL:
![gzle01-2](https://cloud.githubusercontent.com/assets/3253689/9499281/a6a2bcc6-4bec-11e5-8d69-a657c70f447f.png)

**Comment by Tinob** [comment]
this issue is fixed in the latest verion of ishiiruka.
