### ISSUE TITLE
Not Building on Arch (missing hb.h)

### ISSUE THREAD

**Issue by tchici** [Tinob/Ishiiruka#138]
This is not an issue in normal Dolphin.

During build process, it looks for hb.h (and related files), but doesn't find them in /usr/include/. This is because the files are located in /usr/include/harfbuzz/ (at least in Arch).

```
$ pkgconf --cflags harfbuzz
-I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include 
```

I don't know much about programming, but the path might be hard coded in the cmake file(?)

Edit: A workaround for now is to create symbolic links in /usr/include/ to /usr/include/harfbuzz/ for all the files. After that, it builds successfully.

**Comment by treymerkley** [comment]
Did you build by hand or via AUR?

**Comment by tchici** [comment]
Tried both. Both gave same error.

**Comment by treymerkley** [comment]
huh, I can't find where in the codebase it looks for hb. This might be somethig Tino'll have to look at.

**Comment by Tinob** [comment]
Thats a dependency for wx, that is not used anymore in master, the weird thing is that in the included wx code the paths are correct so maybe is something wrong with the native wx package in arch.

**Comment by tchici** [comment]
Attached is output from trying to build. [Building Ishiiruka.txt](https://github.com/Tinob/Ishiiruka/files/3797656/Building.Ishiiruka.txt)
Sorry, couldn't upload to pastebin.

**Snippets**
From cmake:
```
(snip)
-- Could NOT find wxWidgets (missing: wxWidgets_LIBRARIES wxWidgets_INCLUDE_DIRS) (Required is at least version "3.1.0")
(snip)
-- Could NOT find OpenSLES (missing: OPENSLES_LIBRARY OPENSLES_INCLUDE_DIR) 
(snip)
```
There were other stuff not found, but these were the only ones in caps...

From make:
```
(snip)
/usr/include/pango-1.0/pango/pango-coverage.h:28:10: fatal error: hb.h: No such file or directory
   28 | #include <hb.h>
      |          ^~~~~~
compilation terminated.
make[2]: *** [Source/Core/DolphinWX/CMakeFiles/ishiiruka.dir/build.make:1011: Source/Core/DolphinWX/CMakeFiles/ishiiruka.dir/Frame.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1019: Source/Core/DolphinWX/CMakeFiles/ishiiruka.dir/all] Error 2
make: *** [Makefile:152: all] Error 2
```

**Comment by niobium93** [comment]
This used to fail to build for me too, but I tried building the AUR package just now and it built fine, so I guess its fixed now.

**Comment by tchici** [comment]
Thanks for the notice.

I just tried building it both by hand and through the AUR package. It seems to work now without manual intervention (e.g., symlinks). I think I can close this issue now.

I wonder what the problem was. `hb.h` is still in `/usr/include/harfbuzz`. Maybe there was a CMake bug or the CMake configuration was changed.
