### ISSUE TITLE
Build fails with default configuration because of C++20 feature

### ISSUE THREAD

**Issue by tchici** [Tinob/Ishiiruka#146]
`Source/Core/VideoCommon/HiresTextures.cpp` uses member function `starts_with` on a string in lines 324, 328, 343, and 347. This member function was added in C++20, which is still evolving, so many compilers do not enable C++20 features by default or do not support it at all. This means that following the build instructions will not work on many machines without some tweaking.

I can think of two approaches to fix this issue.

One way is to enable C++20 features. For example, in GCC, C++20 features are disabled by default and are enabled by adding `-std=c++2a` (see https://gcc.gnu.org/projects/cxx-status.html). However, I don't know how other compilers will react to this flag, and this still does not address compilers that do not support C++20 features at all.

Another option is to find an alternative to `starts_with`: https://stackoverflow.com/questions/8095088/how-to-check-string-start-in-c/8095132 (from my limited knowledge in C++, Alan Stokes' answer seems to be the best)

**Comment by Tinob** [comment]
should be fixed in the latest version

**Comment by tchici** [comment]
commit 4a732b553896f910e5eb7bec2b72d7a23c7676b4 seems to have addressed this issue
