### ISSUE TITLE
CMake fails on Linux

### ISSUE THREAD

**Issue by blackawps** [Tinob/Ishiiruka#15]
There seems to be a little issue with the OGL backend CMakeFile

`CMake Error: Error in cmake code at
/home/jake/Developer/Ishiiruka/Source/Core/VideoBackends/OGL/CMakeLists.txt:29:
Parse error.  Function missing ending ")".  Instead found unterminated string with text "${S".`

I checked it out and found that the line seems to be incomplete

`add_dolphin_library(videoogl "${S`

I'm assuming it should be this, compared to the original branch of dolphin

`add_dolphin_library(videoogl "${SRCS}" "${LIBS}")`

but then you get this error and I'm pretty much stuck at this point
```
CMake Error at Source/CMakeLists.txt:38 (add_library):
  Cannot find source file:

    GLExtensions/GLExtensions.cpp

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx
Call Stack (most recent call first):
  Source/Core/VideoBackends/OGL/CMakeLists.txt:29 (add_dolphin_library)
```

I did manage to get around that cmake error by changing

`GLExtensions/GLExtensions.cpp`

to

`../../Common/GL/GLExtensions/GLExtensions.cpp`

but I get a ton of make errors, so I feel that's not a real solution.

**Comment by Tinob** [comment]
the last version fix the issues you descrived but core is throwing some errors in linux, will try to merge llatest master to fix that

**Comment by blackawps** [comment]
Closing since it now works on linux
