### ISSUE TITLE
Material Mapping does not work in Zelda: Twilight Princess

### ISSUE THREAD

**Issue by HenrikoMagnifico** [Tinob/Ishiiruka#152]
Hi! I'm trying to get material mapping to work in Zelda: Twilight Princess (GameCube) but it doesn't appear to do anything when I try to use it. I have material map textures (.nrm, .spec, .bump etc) but they don't appear to make any visual difference. I've used Ishiiruka TextureEncoder to merge them too, but that didn't help. Custom textures work just fine, it's only material maps that don't work. It works in other games, only Twilight Princess does not seem to work.

**Specs:**
Windows 10 64-bit
i7-4790K
Nvidia GTX 1070Ti
16GB DDR3

Using the latest version of Ishiiruka Dolphin x64 (1105) on DirectX 11.

Any help would be much appreciated!

Update: It seems specular maps might be working? Textures with high specularity get brighter when Material Mapping is enabled, which to me says they are working. But normal maps are not working, neither are bump maps.

**Comment by Tinob** [comment]
I have different texture packs that are working so must be something wrong inthe configuration or on the files. for it to work you should build the materials files from your raw files using ishiiruka tool, and you should enable pixel ligthing, phong shading, load custom textures and load custom material maps

**Comment by HenrikoMagnifico** [comment]
Thanks for your very quick response! I have now generated the materials with Ishiiruka TextureEncoder, instead of the Custom Texture Tool by Bighead.  It now works perfectly! Thank you :)
