### ISSUE TITLE
How to build and use Env Cubemaps

### ISSUE THREAD

**Issue by HenrikoMagnifico** [Tinob/Ishiiruka#153]
I am confused regarding the newly added feature to Ishiiruka Dolphin, Environment Cubemaps. How does it work? How do I create env cubemaps? How do I use them in Ishiiruka Dolphin, are there any limitations?

Any answers to these questions would be much appreciated. Keep up the awesome work!

Cheers

**Comment by Tinob** [comment]
https://github.com/Tinob/Ishiiruka/wiki/Environmental-Cubemaps

**Comment by HenrikoMagnifico** [comment]
Lovely! Thanks Tino :)
