### ISSUE TITLE
Super Mario Sunshine NTSC-U not saving

### ISSUE THREAD

**Issue by epic-bruh-moment** [Tinob/Ishiiruka#155]
![image](https://user-images.githubusercontent.com/60384541/82319128-dc935580-99f2-11ea-92e8-e7dc25f79b1c.png)
The game was saving my progress until I got 20 shines, savestates do work properly, but I want to fix this, I also have slot A set to GCI folder, where I have been saving all this time

**Comment by Tinob** [comment]
please can you tell me the source of this sissue i was about to investigate about this.
