### ISSUE TITLE
Converting PNG Material Maps to DDS

### ISSUE THREAD

**Issue by HenrikoMagnifico** [Tinob/Ishiiruka#160]
Hi! I'm trying to convert my existing PNG textures into DDS BC7, however it seems the already merged material maps can not be converted by IshiirukaTool or even the Custom Texture Tool by BigHead. It doesn't seem to recognize them as images at all. Is there any other way to convert .mat.png material maps into DDS?

Cheers!

**Comment by Tinob** [comment]
my teture tool should support that scenario clicking in the using existing mterials options if is not working then there is a bug, please confirm it and i will take a look.

**Comment by HenrikoMagnifico** [comment]
> my teture tool should support that scenario clicking in the using existing mterials options if is not working then there is a bug, please confirm it and i will take a look.

That's what I tried, I have tried both using the "Use Existing Materials" option and without it, it never recognizes the material maps. Note that they have been merged previously using IshiirukaTool to the texid.mat.png format.

**Comment by Tinob** [comment]
ok will take alook

**Comment by Tinob** [comment]
https://drive.google.com/file/d/1Tg0niMDJySxkvG-BNEUVnZ7iq8q6AhpV/view?usp=sharing
should work in this version

**Comment by HenrikoMagnifico** [comment]
> https://drive.google.com/file/d/1Tg0niMDJySxkvG-BNEUVnZ7iq8q6AhpV/view?usp=sharing
> should work in this version

This version works perfectly, thank you Tino! :)
