### ISSUE TITLE
Ishiiruka does not yet work with multiple texture IDs like the Main Branch of Dolphin

### ISSUE THREAD

**Issue by HenrikoMagnifico** [Tinob/Ishiiruka#168]
This would be a very neat feature to have in Ishiiruka! What is does is it allows for multiple versions with different game IDs to load the same textures. An example where this is applicable is Twilight Princess textures loading on the Wii version and Pikmin 1 / 2 textures loading on the Wii versions as well. This removes the need of having to rename the folder to the correct ID manually.

**Comment by Tinob** [comment]
did't know about that feature how is working on master?

**Comment by HenrikoMagnifico** [comment]
You simply place a .txt file with the ID as it's name inside the texture
folder for that game (i.e. for Pikmin it would be inside the folder "GPI"
which is the GameCube ID, the custom textures are inside that folder as
well) and the .txt would be named "R9I.txt" in this case because that is
the game ID for the Wii version of Pikmin, which is cross compatible with
it's textures since it uses the same textures as it's GameCube counterpart.
The structure looks like this;

Load
    Textures
        GPI
            CustomTexture.png
            R9I.txt


Den tis 18 aug. 2020 20:43Tinob <notifications@github.com> skrev:

**Comment by Tinob** [comment]
nice will try to add it then

**Comment by HenrikoMagnifico** [comment]
Great, thanks Tino :)

**Comment by Tinob** [comment]
is now implemented in the latest version.

**Comment by HenrikoMagnifico** [comment]
Fantastic and quick work Tino. Thank you!

Den mån 24 aug. 2020 04:04Tinob <notifications@github.com> skrev:
