### ISSUE TITLE
Tessellation and Parallax Occlusion Mapping?

### ISSUE THREAD

**Issue by ADormant** [Tinob/Ishiiruka#20]
We have Bump Mapping already would it be possible to add something even better like Tessellation or Parallax Occlusion Mapping? @Tinob

**Comment by Tinob** [comment]
FIxed in Ishiruka 455 ;)

**Comment by ADormant** [comment]
Wow great, thanks. This is the first emulator with tesselation and displacement mapping as far as I know. Strange no one has ever tried it before. With 6xbrz it will be pretty much perfect. @Tinob

**Comment by ADormant** [comment]
Wow this is great, thanks. This is the first emulator with tesselation and displacement mapping as far as I know. Strange no one has ever tried it before. With 6xbrz Ishiiruka will be pretty much perfect. @Tinob
