### ISSUE TITLE
Missing shader translation

### ISSUE THREAD

**Issue by ADormant** [Tinob/Ishiiruka#25]
The main reason why  DolphinFX wasn't merged the mainstream version was the lack of shader tranlation system(some other emulstor like PPSSPP have it) in Dolphin  https://github.com/dolphin-emu/dolphin/pull/1535 . If you ever manage to add shader translation then it'll make Ishiiruka easier to merge to the master. https://github.com/benvanik/xenia/commit/65130edaa1f503f9f5f934606c13a1122205b3e8

**Comment by ADormant** [comment]
Shader translation  @Tinob https://github.com/benvanik/xenia/commit/65130edaa1f503f9f5f934606c13a1122205b3e8

**Comment by Tinob** [comment]
if by shader translation you mean cross backend portability, isshiiruka already added a common shader interface that allow unnified shader for ogl and dx11. If that is what you meant please tell me so I can close the issue.

**Comment by ADormant** [comment]
No I don't mean cross DX/OpenGL shader compatibility but something else like https://github.com/hrydgard/ppsspp/pull/7467/files
I guess for a more detailed explanation about what is needed we need to ask @neobrain 
@Asmodean- .

**Comment by Tinob** [comment]
fixed in the last version :)

**Comment by ADormant** [comment]
Thanks.
