### ISSUE TITLE
Support for LUTs in post-processing shaders

### ISSUE THREAD

**Issue by ADormant** [Tinob/Ishiiruka#30]
Some shaders require it.

https://github.com/libretro/RetroArch/pull/674/files
https://github.com/libretro/RetroArch/pull/682/files
https://github.com/Armada651/hqx-lut-generator
https://github.com/libretro/common-shaders/tree/master/hqx
http://filthypants.blogspot.com/2012/03/xbr-vs-hqx-interpolation-filter.html

**Comment by ADormant** [comment]
@Tinob https://github.com/libretro/RetroArch/pull/682/files

**Comment by ADormant** [comment]
@Tinob shader pass feedback https://github.com/CautiousAlbino/RetroArch/commit/aee5e74001b77d2f46b697e6ef5d30ae8c5a1374
https://github.com/libretro/RetroArch/pull/2068/files

**Comment by ADormant** [comment]
@Tinob 
Passprev good for chaining multiple post-processing shaders
https://github.com/libretro/RetroArch/commit/b292caf92b103c06eaa3e3c3146d5e1f38ffdaba
https://github.com/libretro/RetroArch/commit/59c64f9c5aa2a4974eda6bfe2a3222f04b102d9d
Mipmapping and SRGB FBO.
https://github.com/libretro/RetroArch/commit/bc8bb1305073de7ac39326127ac311c47605df69
https://github.com/libretro/RetroArch/commit/7559ca12efcbcb31ef02ad6d131c208724971daf
Floating FBO
https://github.com/libretro/RetroArch/commit/773c5111796fc6b3f4deb0f44ea43c8919c0a748
Wrapping modes.
https://github.com/libretro/RetroArch/commit/551fd27204f8e19d2d09e0b574041a9b65b2b82e

**Comment by Tinob** [comment]
already supported in the new shader system so closing
