### ISSUE TITLE
DolphinFX is outdated.

### ISSUE THREAD

**Issue by ADormant** [Tinob/Ishiiruka#31]
@Asmodean-  

https://github.com/PCSX2/pcsx2/blob/master/bin/shaders/GSdx.fx
https://github.com/Tinob/Ishiiruka/blob/master/Data/Sys/Shaders/DolphinFX.glsl
http://forums.pcsx2.net/Thread-Custom-Shaders-for-GSdx?pid=441430#pid441430

**Comment by ADormant** [comment]
@Asmodean-  Could it be updated up to GSdx.fx standard?

**Comment by ADormant** [comment]
Could it be updated up to GSdx.fx standard?

**Comment by ADormant** [comment]
@Tinob DolphinFX seems to have een updated so guess it can be closed now?
https://github.com/Tinob/Ishiiruka/commit/f8e89a79a009335dde2714e71f69a28ea593e202

**Comment by Tinob** [comment]
updated in 524
