### ISSUE TITLE
 A way to load/sample from an external image 

### ISSUE THREAD

**Issue by ADormant** [Tinob/Ishiiruka#34]
A way to load/sample from an external image (some great shading effects use this like Storybook shaders).
http://www.lighthouse3d.com/cg-topics/code-samples/loading-an-image-and-creating-a-texture/
https://www.opengl.org/registry/specs/ARB/shader_image_load_store.txt
https://www.opengl.org/registry/specs/ARB/shader_image_size.txt
https://www.opengl.org/registry/specs/EXT/shader_image_load_store.txt
https://www.opengl.org/registry/specs/ARB/shader_texture_image_samples.txt
https://www.opengl.org/registry/specs/EXT/shader_image_load_formatted.txt
https://www.opengl.org/wiki/Image_Format
https://www.opengl.org/wiki/Image_Libraries
https://www.opengl.org/wiki/Image_Load_Store
https://www.opengl.org/wiki/Image_Load_Store

**Comment by Tinob** [comment]
implemented in the new post procesing backend so i will close this
