### ISSUE TITLE
Emulated clock CPU for x86 build

### ISSUE THREAD

**Issue by dona12345** [Tinob/Ishiiruka#38]
@Tinob can you add this?

**Comment by Tinob** [comment]
what do you call Emulated clock CPU?

**Comment by dona12345** [comment]
I mean this https://www.reddit.com/r/emulation/comments/2s1c83/dolphin_adds_cpu_overclockingunderclocking_support/

**Comment by dona12345** [comment]
@Tinob

**Comment by djbarry004** [comment]
Hey Tino, long time no see in here.

I think he´s referring to the "Override CPU clock" function that it´s in current master.

**Comment by Tinob** [comment]
already merged
