### ISSUE TITLE
Some graphical enhancement sliders have no width on linux

### ISSUE THREAD

**Issue by bkacjios** [Tinob/Ishiiruka#40]
![Image of enhancement tab](http://i.imgur.com/iJuLeFO.png)

Seems on Linux a few of the sliders under the enhancement tab have 0 width, so you are unable to actually customize it at all.

Seems to affect the Lighting Parameters and the Texture Scaling. Tried a bunch of GTK themes and the problem still persists.

**Comment by Tinob** [comment]
this should be fixed in the latest version
