### ISSUE TITLE
Vertex Shader fails to compile

### ISSUE THREAD

**Issue by gamax92** [Tinob/Ishiiruka#50]
Getting a vertex shader compile error when launching all games, and also getting no output from all games besides some solid colors.

```
Failed to compile vertex shader: ~/.dolphin-emu/Dump/bad_vs_0001.txt
Debug info (X.Org, Gallium 0.4 on AMD RV740 (DRM 2.43.0 / 4.4.8-040408-generic, LLVM 3.9.0), 3.3 Mesa 12.1.0-devel - padoka PPA (git-d8d6091)):
0:124(14): error: cannot access field `clipPos' of structure
0:124(14): error: type mismatch
```

The shader in question has been uploaded to a gist here: https://gist.github.com/gamax92/18f56a318f7ae8305ad168eaddbf7f96

EDIT:
Changing line 513 of VertexShaderGen.cpp from ```out.Write("  clipPos_2 = o.clipPos;\n");``` to ```out.Write("  clipPos_2 = o.clipPos_2;\n");``` seems to fix the issue, I don't get compile errors and visuals are working.

**Comment by Tinob** [comment]
thanks for the report your fix will be present on the next version

**Comment by Tinob** [comment]
should be fixed in 705 please confirm to close the issue

**Comment by gamax92** [comment]
Don't know what 705 is but thanks, fixed.
