### ISSUE TITLE
No More Heroes graphics corruption in 727

### ISSUE THREAD

**Issue by Deepo** [Tinob/Ishiiruka#52]
Hi.

There seems to have been introduced some graphics corruption on No More Heroes (RNHE41)  in all builds after 721.

I have the following in the game settings file:
[Video_Hacks]
EFBToTextureEnable = False

Happens with all renderers, (Can't get software renderer to work).

Here are shots from 727:
![2016-08-09 2](https://cloud.githubusercontent.com/assets/2171572/17533983/7560779e-5e87-11e6-9318-da1c926fa4c6.png)
![2016-08-09 4](https://cloud.githubusercontent.com/assets/2171572/17534007/8534c30a-5e87-11e6-8d2b-3b36a63277e3.png)

Here are shots from 721 for reference:
![2016-08-09 5](https://cloud.githubusercontent.com/assets/2171572/17534026/9426fc98-5e87-11e6-8b78-1851810151de.png)
![2016-08-09 6](https://cloud.githubusercontent.com/assets/2171572/17534034/99a0a23c-5e87-11e6-8c84-f5652629ff17.png)

The screens are using DX12.

I have attached my Ishiiruka config and my dxdiag:
[Ishiiruka Config.zip](https://github.com/Tinob/Ishiiruka/files/409901/Ishiiruka.Config.zip)
[DxDiag.txt](https://github.com/Tinob/Ishiiruka/files/409903/DxDiag.txt)

I'm running Windows 10 1511 and a Nvidia card on driver 368.81.

Please let me know if I can provide more info.

**Comment by Tinob** [comment]
thanks for the report can you please make a fifolog of those frames so i can test myself for a fix

**Comment by Deepo** [comment]
I will do it first thing in the morning.

Any recommendations on the number of frames to record? Is 1 per scene enough, or should I record several? Thanks.

**Comment by Tinob** [comment]
1 or 2 will work

**Comment by Tinob** [comment]
please test version 747 i thing i find and fix this issue, please confirm if that is that is the case

**Comment by Deepo** [comment]
Fixed in 747, thanks!
