### ISSUE TITLE
DolphinFX Scanlines On/Off Switch Broken

### ISSUE THREAD

**Issue by shinra358** [Tinob/Ishiiruka#60]
Once you turn them on and then turn them off, when you reset the emulator, they will always appear on again.

Newest version to this date of this version of the emu. Opengl backend.

**Comment by Tinob** [comment]
when did you turn them off? if you turn them on while no game is running the settings is applied globally, if you turn them on while a game is running it only applied for that specific game. turning it off while the game is running will only turn it off for that specific game.

**Comment by shinra358** [comment]
Ok, gotcha. Didn't know the per game config was done that way now. Been a while.
