### ISSUE TITLE
ubuntu compiling error

### ISSUE THREAD

**Issue by popcorn9499** [Tinob/Ishiiruka#66]
it fails to run make  cmake seems to work but make fails. anything u need to me to do let me know. 
The logs are here. [cmake log](http://pastebin.com/3BDz7149)  [make log](http://pastebin.com/WDVyzpWE)

If i missed anything tell me. Hopefully this is fixable

**Comment by Tinob** [comment]
I'm not currently at home, this weekend will take a look. Thanks for the report.

**Comment by popcorn9499** [comment]
Thanks. I'll try and respond as quick as possible. on a side note for the problem dolphin compiles fine since i tried compiling a dev build of that too

**Comment by maxpoulin64** [comment]
I was able to successfully build it by simply removing the `PowerPC/CachedInterpreter.cpp` line in `Source/Core/Core/CMakeLists.txt:185`.

Looks like it was moved in bb7e09d91ca268b5233384911dee41ba16839fa4 and the new location added, but the old one was not removed.

**Comment by Tinob** [comment]
nice finding will try to fix it when i get home

**Comment by popcorn9499** [comment]
just figured id let u know that it seems removing the line 185 in that file worked. Thanks. Im gonna continue testing to see if that works well or if it fails. Hopefully that was all that was wrong.

**Comment by Tinob** [comment]
fixed in latest version
