### ISSUE TITLE
Linux make error

### ISSUE THREAD

**Issue by popcorn9499** [Tinob/Ishiiruka#69]
When i try to build ishiiruka it suddenly wouldnt build. i tried making sure the dependancies were there but 
it failed still. It gives me this [error](http://pastebin.com/pSJNX6xG)

versions:
ubuntu: 16.04
make: 4.1
im not sure what else you would like me to give you. If u want more info ill gladly give it to u.

**Comment by oCanna** [comment]
Same issue here with (K)ubuntu 16.04. The following patch works for me. 

```
diff --git a/Externals/xbrz/CMakeLists.txt b/Externals/xbrz/CMakeLists.txt
index 36228bc..6a273a4 100644
--- a/Externals/xbrz/CMakeLists.txt
+++ b/Externals/xbrz/CMakeLists.txt
@@ -4,5 +4,8 @@ set(SRCS
        xbrz.cpp
 )

+if(${CMAKE_SYSTEM_NAME} STREQUAL "Linux")
+       set_source_files_properties(${SRCS} PROPERTIES COMPILE_FLAGS -std=gnu++14)
+endif()

 add_library(xbrz STATIC ${SRCS})
```

**Comment by popcorn9499** [comment]
So i just would add that to the cmakelists file or am is that me replacing stuff? Thanks ill try it once i understand what ur meaning

**Comment by oCanna** [comment]
Yes, you have just to add those three lines. Without the leading plus signs of course ;)

**Comment by Tinob** [comment]
fixed in latest version
