### ISSUE TITLE
Linux Build fails 

### ISSUE THREAD

**Issue by TheGitJay** [Tinob/Ishiiruka#70]
Hi Tinob

Trying to build the linux version but it fails, both the install and portable method

`/home/jay/Downloads/Ishiiruka-master/Source/Core/VideoCommon/VertexLoaderManager.cpp:104:119: error: ‘StringFromFormat’ was not declared in this scope
 filename = StringFromFormat("%sG_%s_pvt.h", File::GetUserPath(D_DUMP_IDX).c_str(), last_game_code.c_str());
                                                                                                          ^
make[2]: *** [Source/Core/VideoCommon/CMakeFiles/videocommon.dir/build.make:1407: Source/Core/VideoCommon/CMakeFiles/videocommon.dir/VertexLoaderManager.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1701: Source/Core/VideoCommon/CMakeFiles/videocommon.dir/all] Error 2
make: *** [Makefile:161: all] Error 2
`
Do you have any advice on how to solve this?

Thank you

**Comment by Tinob** [comment]
you should add
#include "Common/StringUtil.h"
to line 15 of VertexLoaderManager.cpp and it should solve the issue

**Comment by TheGitJay** [comment]
Hi Tinob

Thanks for getting back to me, Im having trouble locating VertexLoaderManager.cpp, after 

`make`

in /Ishiiruka-master/build/Source/Core/VideoCommon/CMakeFiles , all I can find is VertexLoader.cpp.o , VertexLoaderBase.cpp.o and VertexLoaderCompiled.cpp.o 

can you advise me where I should find VertexLoaderManager.cpp to add #include "Common/StringUtil.h"  ?

Thank you for your help, I appreciate it

**Comment by Tinob** [comment]
it should be in this path
/Ishiiruka-master/build/Source/Core/VideoCommon/VertexLoaderManager.cpp

**Comment by TheGitJay** [comment]
Im not seeing it here

this is the method I've been doing

`
    mkdir build
    cd build
    cmake ..
    make
`
after make, it fails, so I should locate 

/Ishiiruka-master/build/Source/Core/VideoCommon/VertexLoaderManager.cpp 

and #include "Common/StringUtil.h" to line 15 of VertexLoaderManager.cpp

but VertexLoaderManager.cpp doesn't appear after the failed build? 

if there's any logs or something that i can post to help I can do that?

Thank you

**Comment by Tinob** [comment]
you can use
make &> compileout.txt and send me the file so i can see the errors myself.

**Comment by TheGitJay** [comment]
Here you go, Thanks for your help.

[compileout.txt](https://github.com/Tinob/Ishiiruka/files/832182/compileout.txt)

**Comment by Tinob** [comment]
the error is the missing line in this file
/home/jay/Downloads/Ishiiruka-master/Source/Core/VideoCommon/VertexLoaderManager.cpp you have to edit the file and add the line and re run the make command and it should work.

**Comment by TheGitJay** [comment]
but /Ishiiruka-master/Source/Core/VideoCommon/VertexLoaderManager.cpp doesnt appear after a failed build, should I create VertexLoaderManager.cpp manually anyway and add the line and then run make again?

**Comment by Tinob** [comment]
the file should exist or else the compiler will fail with a missing source file, are you shure you are looking in the correct folder?

**Comment by TheGitJay** [comment]
i'm pretty sure i was looking in the correct place, i simply copied the location and it wasn't there, I've started a new build to be sure, ill message back soon

**Comment by Tinob** [comment]
the file is part of the source code you downloaded so it must be in the videocommon folder

**Comment by TheGitJay** [comment]
Yes! works now, the initial confusion was I first looked here

/Ishiiruka-master/build/Source/Core/VideoCommon/VertexLoaderManager.cpp

when i should have looked here

/Ishiiruka-master/Source/Core/VideoCommon/VertexLoaderManager.cpp

Thanks for all your help, and thanks for Ishiiruka! really really appreciate it

**Comment by Tinob** [comment]
nice will uploaded the fix to the repository.
