### ISSUE TITLE
(Fix included) macOS Not building with C++14 plus one other misc error

### ISSUE THREAD

**Issue by LeonBlade** [Tinob/Ishiiruka#73]
There's a problem with how the default cmake config is setup for macOS at least from my Mac.  The fixes I employed were to just chuck...

```cmake
set(CMAKE_CXX_STANDARD 14)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
```

...in the config and then it builds everything ends up building fine.

There's one other misc error I'm just gonna toss in this issue:
```
/Users/LeonBlade/Development/Ishiiruka/Source/Core/AudioCommon/SoundStream.cpp:164:33: error: no
      member named 'fminf' in namespace 'std'; did you mean simply 'fminf'?
                                ratemultiplier = std::fmaxf(std::fminf((float)availablesampl...
                                                            ^~~~~~~~~~
                                                            fminf
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include/math.h:549:14: note: 
      'fminf' declared here
extern float fminf(float, float);
```

The solution is to just chop `std::` off the front of the `fminf` and `fmaxf` for macOS.

**Comment by Tinob** [comment]
can you give me more detail on how to add you fix to the cmake files_ after you compiled it succesfully how it is working on mac?

**Comment by LeonBlade** [comment]
@Tinob Hey, so, I added those lines after https://github.com/Tinob/Ishiiruka/blob/master/CMakeLists.txt#L41 and then just ran the normal build instructions on readme.  Sorry for the confusion.

It's not working successfully on the Mac I'm afraid, it looks like this: http://i.imgur.com/oOQiLWB.png

Lots of problems with the graphics I'm afraid.  The actual game seems to run fine, audio seems fine, input seems fine, but the graphics are certainly broken.

**Comment by Tinob** [comment]
this should be working now with the latets version can you pleae configrm?

**Comment by LeonBlade** [comment]
Sorry for not getting back to you on this.  I compiled it fine, but one of the shaders isn't working.  I can create a new issue or just post the log here.

**Comment by Tinob** [comment]
please create a new issue so i can track it
