### ISSUE TITLE
Linux build failure

### ISSUE THREAD

**Issue by KAMiKAZOW** [Tinob/Ishiiruka#80]
[  417s] [ 41%] Building CXX object Source/Core/VideoCommon/CMakeFiles/videocommon.dir/PostProcessing.cpp.o
[  418s] /home/abuild/rpmbuild/BUILD/ishiiruka-dolphin-unstable-5.0.20170504+git.89fd4df/Source/Core/VideoCommon/PostProcessing.cpp:29:25: fatal error: wx/language.h: No such file or directory
[  418s]  #include <wx/language.h>
[  418s]                          ^
[  418s] compilation terminated.
[  418s] make[2]: *** [Source/Core/VideoCommon/CMakeFiles/videocommon.dir/build.make:1119: Source/Core/VideoCommon/CMakeFiles/videocommon.dir/PostProcessing.cpp.o] Error 1
[  418s] make[1]: *** [CMakeFiles/Makefile2:1183: Source/Core/VideoCommon/CMakeFiles/videocommon.dir/all] Error 2
[  418s] make: *** [Makefile:161: all] Error 2
[  418s] error: Bad exit status from /var/tmp/rpm-tmp.wTJOLi (%build)

Complete log: https://build.opensuse.org/build/home:KAMiKAZOW:Emulators/openSUSE_Tumbleweed/x86_64/ishiiruka-dolphin-unstable/_log

**Comment by Tinob** [comment]
should be fixed in the last version

**Comment by KAMiKAZOW** [comment]
Tried again. Sadly no. The error message changed, though: https://build.opensuse.org/package/live_build_log/home:KAMiKAZOW:Emulators/ishiiruka-dolphin-unstable/Fedora_25/x86_64

**Comment by Tinob** [comment]
Now it should be fixed

**Comment by KAMiKAZOW** [comment]
Yep
