### ISSUE TITLE
Black screen with Nvidia drivers

### ISSUE THREAD

**Issue by robattila128** [Tinob/Ishiiruka#81]
Hi I can only get Ishiiruka to run with Nouveau kernel drivers, that is not the case in the main Dolphin. I am using [nvidia-340xx](https://www.archlinux.org/packages/extra/x86_64/nvidia-340xx/) with a GeForce 9600 GT and Arch Linux. Commit is Ishiiruka#0b00f1f6267190a8bf9a3584497a35d8762eb0a9

The console output does not display any errors. I can only hear game music.
https://i.imgur.com/a7ccip7.png

**Comment by Tinob** [comment]
i have no way to reproduce your issue, can you give me more info?

**Comment by ccl2of4** [comment]
Which video backend are you using (vulkan/opengl)? If you are using vulkan, try opengl; or vice versa
