### ISSUE TITLE
Error when opening "Config" gui

### ISSUE THREAD

**Issue by ccl2of4** [Tinob/Ishiiruka#84]
Intermittently (~50% of the time), when I open the "Config" gui by pressing the "Config" button, I get the following errors dumped out in the console

```
(dolphin-emu:11295): Gdk-CRITICAL **: IA__gdk_screen_get_monitor_geometry: assertion 'monitor_num >= 0' failed

(dolphin-emu:11295): Gdk-CRITICAL **: IA__gdk_screen_get_monitor_geometry: assertion 'monitor_num >= 0' failed

(dolphin-emu:11295): Gtk-CRITICAL **: IA__gtk_window_resize: assertion 'width > 0' failed
```

More importantly though, the "Config" window itself comes in at what I think is a very tiny resolution. You can see in this screenshot that it comes in as what appears to be a vertical black line (near the center of the window).

![screenshot_2017-05-25_18-13-49](https://cloud.githubusercontent.com/assets/8164297/26474521/17db8bf8-4177-11e7-8642-46127be06938.png)

I do not experience this issue on any previous faster melee netplay versions (4.3, 4.4), and I also do not experience this issue with the latest commit from dolphin master (d592bdd).

Specs:
OS: Arch Linux
DE: xfce4
GPU: nvidia 970
Monitor: 3@1920x1080
Ishiiruka: d462ca387 (Faster melee v5.0.3)

Thank you and let me know if I can provide any more information to help :smile:

**Comment by KAMiKAZOW** [comment]
Educated guess: Either the wxWidgets version you're using or your Xfce theme is to blame.

I can't reproduce either behavior under Fedora 25 (which uses the bundled wx version because 3.1 is not available in the repos).
