### ISSUE TITLE
Linux compilation error

### ISSUE THREAD

**Issue by KAMiKAZOW** [Tinob/Ishiiruka#88]
[  647s] [ 43%] Building CXX object Source/Core/VideoCommon/CMakeFiles/videocommon.dir/TextureScalerCommon.cpp.o

[  648s] In file included from /home/abuild/rpmbuild/BUILD/ishiiruka-dolphin-unstable-5.0.20170625+git.64a95ca5e/Source/Core/VideoCommon/TextureScalerCommon.cpp:33:0:

[  648s] /home/abuild/rpmbuild/BUILD/ishiiruka-dolphin-unstable-5.0.20170625+git.64a95ca5e/Source/Core/Common/ThreadPool.h:464:23: error: 'function' is not a member of 'std'

[  648s]   ManyToManyQueue<std::function<void()>, CircularQueue<std::function<void()>>> m_TaskQueue;

[  648s]                        ^~~~~~~~

[  648s] /home/abuild/rpmbuild/BUILD/ishiiruka-dolphin-unstable-5.0.20170625+git.64a95ca5e/Source/Core/Common/ThreadPool.h:464:23: note: suggested alternative: 'is_function'

[  648s]   ManyToManyQueue<std::function<void()>, CircularQueue<std::function<void()>>> m_TaskQueue;

[  648s]                        ^~~~~~~~

[  648s]                        is_function

[  648s] /home/abuild/rpmbuild/BUILD/ishiiruka-dolphin-unstable-5.0.20170625+git.64a95ca5e/Source/Core/Common/ThreadPool.h:464:23: error: 'function' is not a member of 'std'

[  648s] /home/abuild/rpmbuild/BUILD/ishiiruka-dolphin-unstable-5.0.20170625+git.64a95ca5e/Source/Core/Common/ThreadPool.h:464:23: note: suggested alternative: 'is_function'

[  648s]   ManyToManyQueue<std::function<void()>, CircularQueue<std::function<void()>>> m_TaskQueue;

[  648s]                        ^~~~~~~~

[  648s]                        is_function

[  648s] /home/abuild/rpmbuild/BUILD/ishiiruka-dolphin-unstable-5.0.20170625+git.64a95ca5e/Source/Core/Common/ThreadPool.h:464:38: error: template argument 1 is invalid

[  648s]   ManyToManyQueue<std::function<void()>, CircularQueue<std::function<void()>>> m_TaskQueue;

[  648s]                                       ^

[  648s] /home/abuild/rpmbuild/BUILD/ishiiruka-dolphin-unstable-5.0.20170625+git.64a95ca5e/Source/Core/Common/ThreadPool.h:464:38: error: template argument 2 is invalid

[  648s] /home/abuild/rpmbuild/BUILD/ishiiruka-dolphin-unstable-5.0.20170625+git.64a95ca5e/Source/Core/Common/ThreadPool.h:464:39: error: expected unqualified-id before ',' token

[  648s]   ManyToManyQueue<std::function<void()>, CircularQueue<std::function<void()>>> m_TaskQueue;

[  648s]                                        ^

[  648s] /home/abuild/rpmbuild/BUILD/ishiiruka-dolphin-unstable-5.0.20170625+git.64a95ca5e/Source/Core/Common/ThreadPool.h:470:32: error: 'std::function' has not been declared

[  648s]   static void ExecuteAsync(std::function<void()> &&func);

[  648s]                                 ^~~~~~~~

[  648s] /home/abuild/rpmbuild/BUILD/ishiiruka-dolphin-unstable-5.0.20170625+git.64a95ca5e/Source/Core/Common/ThreadPool.h:470:40: error: expected ',' or '...' before '<' token

[  648s]   static void ExecuteAsync(std::function<void()> &&func);

[  648s]                                         ^

[  649s] make[2]: *** [Source/Core/VideoCommon/CMakeFiles/videocommon.dir/build.make:1311: Source/Core/VideoCommon/CMakeFiles/videocommon.dir/TextureScalerCommon.cpp.o] Error 1

[  649s] make[1]: *** [CMakeFiles/Makefile2:1183: Source/Core/VideoCommon/CMakeFiles/videocommon.dir/all] Error 2

[  649s] make: *** [Makefile:163: all] Error 2

[  649s] error: Bad exit status from /var/tmp/rpm-tmp.glPP7n (%build)

See https://build.opensuse.org/package/live_build_log/home:KAMiKAZOW:Emulators/ishiiruka-dolphin-unstable/openSUSE_Tumbleweed/x86_64`

**Comment by Tinob** [comment]
should be fixed now
