### ISSUE TITLE
Compile error in linux

### ISSUE THREAD

**Issue by tescorg** [Tinob/Ishiiruka#89]
Running arch linux, unable to compile with this error:

`[ 65%] Building CXX object Source/Core/VideoCommon/CMakeFiles/videocommon.dir/AsyncRequests.cpp.o
In file included from /home/ross/source/Ishiiruka/Source/Core/VideoCommon/NativeVertexFormat.h:13:0,
                 from /home/ross/source/Ishiiruka/Source/Core/VideoCommon/BoundingBox.h:7,
                 from /home/ross/source/Ishiiruka/Source/Core/VideoCommon/AsyncRequests.cpp:8:
/home/ross/source/Ishiiruka/Source/Core/VideoCommon/DataReader.h:13:3: error: ‘__forceinline’ does not name a type; did you mean ‘__mempcpy_inline’?
   __forceinline DataReader()
   ^~~~~~~~~~~~~
   __mempcpy_inline
/home/ross/source/Ishiiruka/Source/Core/VideoCommon/DataReader.h:17:3: error: ‘__forceinline’ does not name a type; did you mean ‘__mempcpy_inline’?
   __forceinline DataReader(u8* src, u8* _end)
   ^~~~~~~~~~~~~
   __mempcpy_inline
/home/ross/source/Ishiiruka/Source/Core/VideoCommon/DataReader.h:21:3: error: ‘__forceinline’ does not name a type; did you mean ‘__mempcpy_inline’?
   __forceinline const u8* GetPointer() const
   ^~~~~~~~~~~~~
   __mempcpy_inline
/home/ross/source/Ishiiruka/Source/Core/VideoCommon/DataReader.h:26:3: error: ‘__forceinline’ does not name a type; did you mean ‘__mempcpy_inline’?
   __forceinline u8* operator=(u8* src)
   ^~~~~~~~~~~~~
   __mempcpy_inline
/home/ross/source/Ishiiruka/Source/Core/VideoCommon/DataReader.h:32:3: error: ‘__forceinline’ does not name a type; did you mean ‘__mempcpy_inline’?
   __forceinline size_t size() const
   ^~~~~~~~~~~~~
   __mempcpy_inline
/home/ross/source/Ishiiruka/Source/Core/VideoCommon/DataReader.h:36:3: error: ‘__forceinline’ does not name a type; did you mean ‘__mempcpy_inline’?
   __forceinline void ReadSkip(u32 skip)
   ^~~~~~~~~~~~~
   __mempcpy_inline
/home/ross/source/Ishiiruka/Source/Core/VideoCommon/DataReader.h:41:25: error: ‘__forceinline’ does not name a type; did you mean ‘__mempcpy_inline’?
   template <typename T> __forceinline T Peek(s32 _uOffset) const
                         ^~~~~~~~~~~~~
                         __mempcpy_inline
/home/ross/source/Ishiiruka/Source/Core/VideoCommon/DataReader.h:47:25: error: ‘__forceinline’ does not name a type; did you mean ‘__mempcpy_inline’?
   template <typename T> __forceinline T Peek() const
                         ^~~~~~~~~~~~~
                         __mempcpy_inline
/home/ross/source/Ishiiruka/Source/Core/VideoCommon/DataReader.h:53:25: error: ‘__forceinline’ does not name a type; did you mean ‘__mempcpy_inline’?
   template <typename T> __forceinline T PeekUnswapped(s32 _uOffset) const
                         ^~~~~~~~~~~~~
                         __mempcpy_inline
/home/ross/source/Ishiiruka/Source/Core/VideoCommon/DataReader.h:59:25: error: ‘__forceinline’ does not name a type; did you mean ‘__mempcpy_inline’?
   template <typename T> __forceinline T PeekUnswapped() const
                         ^~~~~~~~~~~~~
                         __mempcpy_inline
/home/ross/source/Ishiiruka/Source/Core/VideoCommon/DataReader.h:65:43: error: ‘__forceinline’ does not name a type; did you mean ‘__mempcpy_inline’?
   template <typename T, bool swap = true> __forceinline T Read()
                                           ^~~~~~~~~~~~~
                                           __mempcpy_inline
/home/ross/source/Ishiiruka/Source/Core/VideoCommon/DataReader.h:76:25: error: ‘__forceinline’ does not name a type; did you mean ‘__mempcpy_inline’?
   template <typename T> __forceinline T ReadUnswapped()
                         ^~~~~~~~~~~~~
                         __mempcpy_inline
/home/ross/source/Ishiiruka/Source/Core/VideoCommon/DataReader.h:83:3: error: ‘__forceinline’ does not name a type; did you mean ‘__mempcpy_inline’?
   __forceinline u8* GetReadPosition() const
   ^~~~~~~~~~~~~
   __mempcpy_inline
/home/ross/source/Ishiiruka/Source/Core/VideoCommon/DataReader.h:88:3: error: ‘__forceinline’ does not name a type; did you mean ‘__mempcpy_inline’?
   __forceinline u8* GetEnd() const
   ^~~~~~~~~~~~~
   __mempcpy_inline
/home/ross/source/Ishiiruka/Source/Core/VideoCommon/DataReader.h:93:3: error: ‘__forceinline’ does not name a type; did you mean ‘__mempcpy_inline’?
   __forceinline void SetReadPosition(u8 *source, u8 *e)
   ^~~~~~~~~~~~~
   __mempcpy_inline
/home/ross/source/Ishiiruka/Source/Core/VideoCommon/DataReader.h:99:3: error: ‘__forceinline’ does not name a type; did you mean ‘__mempcpy_inline’?
   __forceinline void SetReadPosition(u8 *source)
   ^~~~~~~~~~~~~
   __mempcpy_inline
/home/ross/source/Ishiiruka/Source/Core/VideoCommon/DataReader.h:105:3: error: ‘__forceinline’ does not name a type; did you mean ‘__mempcpy_inline’?
   __forceinline void ReadU32xN(u32 *dst)
   ^~~~~~~~~~~~~
   __mempcpy_inline
/home/ross/source/Ishiiruka/Source/Core/VideoCommon/DataReader.h:134:3: error: ‘__forceinline’ does not name a type; did you mean ‘__mempcpy_inline’?
   __forceinline DataWriter(u8 *destination) : Wbuffer(destination)
   ^~~~~~~~~~~~~
   __mempcpy_inline
/home/ross/source/Ishiiruka/Source/Core/VideoCommon/DataReader.h:136:3: error: ‘__forceinline’ does not name a type; did you mean ‘__mempcpy_inline’?
   __forceinline DataWriter() : Wbuffer(nullptr)
   ^~~~~~~~~~~~~
   __mempcpy_inline
/home/ross/source/Ishiiruka/Source/Core/VideoCommon/DataReader.h:138:3: error: ‘__forceinline’ does not name a type; did you mean ‘__mempcpy_inline’?
   __forceinline void WriteSkip(u32 skip)
   ^~~~~~~~~~~~~
   __mempcpy_inline
/home/ross/source/Ishiiruka/Source/Core/VideoCommon/DataReader.h:143:25: error: ‘__forceinline’ does not name a type; did you mean ‘__mempcpy_inline’?
   template <typename T> __forceinline void Write(T data)
                         ^~~~~~~~~~~~~
                         __mempcpy_inline
/home/ross/source/Ishiiruka/Source/Core/VideoCommon/DataReader.h:149:3: error: ‘__forceinline’ does not name a type; did you mean ‘__mempcpy_inline’?
   __forceinline u8* GetWritePosition() const
   ^~~~~~~~~~~~~
   __mempcpy_inline
/home/ross/source/Ishiiruka/Source/Core/VideoCommon/DataReader.h:154:3: error: ‘__forceinline’ does not name a type; did you mean ‘__mempcpy_inline’?
   __forceinline void SetWritePosition(u8 *destination)
   ^~~~~~~~~~~~~
   __mempcpy_inline
In file included from /home/ross/source/Ishiiruka/Source/Core/VideoCommon/BoundingBox.h:7:0,
                 from /home/ross/source/Ishiiruka/Source/Core/VideoCommon/AsyncRequests.cpp:8:
/home/ross/source/Ishiiruka/Source/Core/VideoCommon/NativeVertexFormat.h: In constructor ‘TPipelineState::TPipelineState(u8*, u8*, u8*)’:
/home/ross/source/Ishiiruka/Source/Core/VideoCommon/NativeVertexFormat.h:68:107: error: no matching function for call to ‘DataReader::DataReader(u8*&, u8*&)’
   TPipelineState(u8* source, u8* _end, u8* destination) : DataReader(source, _end), DataWriter(destination)
                                                                                                           ^
In file included from /home/ross/source/Ishiiruka/Source/Core/VideoCommon/NativeVertexFormat.h:13:0,
                 from /home/ross/source/Ishiiruka/Source/Core/VideoCommon/BoundingBox.h:7,
                 from /home/ross/source/Ishiiruka/Source/Core/VideoCommon/AsyncRequests.cpp:8:
/home/ross/source/Ishiiruka/Source/Core/VideoCommon/DataReader.h:10:7: note: candidate: DataReader::DataReader()
 class DataReader
       ^~~~~~~~~~
/home/ross/source/Ishiiruka/Source/Core/VideoCommon/DataReader.h:10:7: note:   candidate expects 0 arguments, 2 provided
/home/ross/source/Ishiiruka/Source/Core/VideoCommon/DataReader.h:10:7: note: candidate: constexpr DataReader::DataReader(const DataReader&)
/home/ross/source/Ishiiruka/Source/Core/VideoCommon/DataReader.h:10:7: note:   candidate expects 1 argument, 2 provided
/home/ross/source/Ishiiruka/Source/Core/VideoCommon/DataReader.h:10:7: note: candidate: constexpr DataReader::DataReader(DataReader&&)
/home/ross/source/Ishiiruka/Source/Core/VideoCommon/DataReader.h:10:7: note:   candidate expects 1 argument, 2 provided
In file included from /home/ross/source/Ishiiruka/Source/Core/VideoCommon/BoundingBox.h:7:0,
                 from /home/ross/source/Ishiiruka/Source/Core/VideoCommon/AsyncRequests.cpp:8:
/home/ross/source/Ishiiruka/Source/Core/VideoCommon/NativeVertexFormat.h:68:107: error: no matching function for call to ‘DataWriter::DataWriter(u8*&)’
   TPipelineState(u8* source, u8* _end, u8* destination) : DataReader(source, _end), DataWriter(destination)
                                                                                                           ^
In file included from /home/ross/source/Ishiiruka/Source/Core/VideoCommon/NativeVertexFormat.h:13:0,
                 from /home/ross/source/Ishiiruka/Source/Core/VideoCommon/BoundingBox.h:7,
                 from /home/ross/source/Ishiiruka/Source/Core/VideoCommon/AsyncRequests.cpp:8:
/home/ross/source/Ishiiruka/Source/Core/VideoCommon/DataReader.h:131:7: note: candidate: DataWriter::DataWriter()
 class DataWriter
       ^~~~~~~~~~
/home/ross/source/Ishiiruka/Source/Core/VideoCommon/DataReader.h:131:7: note:   candidate expects 0 arguments, 1 provided
/home/ross/source/Ishiiruka/Source/Core/VideoCommon/DataReader.h:131:7: note: candidate: constexpr DataWriter::DataWriter(const DataWriter&)
/home/ross/source/Ishiiruka/Source/Core/VideoCommon/DataReader.h:131:7: note:   no known conversion for argument 1 from ‘u8* {aka unsigned char*}’ to ‘const DataWriter&’
/home/ross/source/Ishiiruka/Source/Core/VideoCommon/DataReader.h:131:7: note: candidate: constexpr DataWriter::DataWriter(DataWriter&&)
/home/ross/source/Ishiiruka/Source/Core/VideoCommon/DataReader.h:131:7: note:   no known conversion for argument 1 from ‘u8* {aka unsigned char*}’ to ‘DataWriter&&’
In file included from /home/ross/source/Ishiiruka/Source/Core/VideoCommon/BoundingBox.h:7:0,
                 from /home/ross/source/Ishiiruka/Source/Core/VideoCommon/AsyncRequests.cpp:8:
/home/ross/source/Ishiiruka/Source/Core/VideoCommon/NativeVertexFormat.h: In member function ‘void TPipelineState::Initialize(u8*, u8*, u8*)’:
/home/ross/source/Ishiiruka/Source/Core/VideoCommon/NativeVertexFormat.h:78:17: error: ‘SetReadPosition’ is not a member of ‘DataReader’
     DataReader::SetReadPosition(source, _end);
                 ^~~~~~~~~~~~~~~
/home/ross/source/Ishiiruka/Source/Core/VideoCommon/NativeVertexFormat.h:79:17: error: ‘SetWritePosition’ is not a member of ‘DataWriter’
     DataWriter::SetWritePosition(destination);
                 ^~~~~~~~~~~~~~~~
In file included from /home/ross/source/Ishiiruka/Source/Core/VideoCommon/AsyncRequests.cpp:8:0:
/home/ross/source/Ishiiruka/Source/Core/VideoCommon/BoundingBox.h: At global scope:
/home/ross/source/Ishiiruka/Source/Core/VideoCommon/BoundingBox.h:31:1: error: ‘__forceinline’ does not name a type; did you mean ‘__mempcpy_inline’?
 __forceinline void SetVertexBufferPosition(TPipelineState &pipelinestate)
 ^~~~~~~~~~~~~
 __mempcpy_inline
make[2]: *** [Source/Core/VideoCommon/CMakeFiles/videocommon.dir/build.make:63: Source/Core/VideoCommon/CMakeFiles/videocommon.dir/AsyncRequests.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1692: Source/Core/VideoCommon/CMakeFiles/videocommon.dir/all] Error 2
make: *** [Makefile:152: all] Error 2
`

**Comment by KAMiKAZOW** [comment]
The Master branch builds fine now but the second compilation fix must also be applied to the Stable branch.

**Comment by Tinob** [comment]
what specific change?

**Comment by KAMiKAZOW** [comment]
https://github.com/Tinob/Ishiiruka/commits/Stable – a single "fix for linux compilation"
https://github.com/Tinob/Ishiiruka/commits/master – additional commits regarding Linux compilation.

Not a developer, so I don't see anything more. Details: https://build.opensuse.org/package/live_build_log/home:KAMiKAZOW:Emulators/ishiiruka-dolphin/openSUSE_Tumbleweed/x86_64

**Comment by Tinob** [comment]
already applyed and compiling on stable and master.

**Comment by Tinob** [comment]
can you please confirm idf theissue is solved for you?

**Comment by tescorg** [comment]
Compiles just fine. :)
