### ISSUE TITLE
Linux compilation error

### ISSUE THREAD

**Issue by Tinob** [Tinob/Ishiiruka#9]

**Comment by rolandg** [comment]
Is a Linux compilation possible without HLSLCompiler.h/D3Dcompiler.h?
I trieed compiling and fixed some of the smaller errors but couldn't resolve that problem.

**Comment by Tinob** [comment]
Not needed yo can use an ifdef an remove it on non windows targets. Tanks for taking the time.

**Comment by rolandg** [comment]
thanks that helped.. 
but I'm running into another error: https://gist.github.com/rolandg/53f2ea771afe8ef63c9b
let me know if you have an idea..

**Comment by Tinob** [comment]
about the opencl files you can remove them because opencl support is currently disabled, my plan was to  use  opencl to support gpu decoding on opengl but that can wait. about the other warnings, you should move InterpretDIsplayList above Decode and that will fix the warnings.

**Comment by rolandg** [comment]
thank you!
but i got stuck again..

/usr/bin/ld: cannot find -luicommon

https://gist.github.com/rolandg/ff131b94d84e089356b6

**Comment by Tinob** [comment]
Add this line
add_subdirectory(UICommon)
inside the file CMakeLists.txt file located at
\Source\Core
and it should work.

**Comment by Tinob** [comment]
Fixed
