### ISSUE TITLE
Compilation of ubershaders on exclusive happens regardless of settings.

### ISSUE THREAD

**Issue by slawekwaga** [Tinob/Ishiiruka#99]
Upon compiling commit Tinob/Ishiiruka@3f5c5e512d9ecbf91d42a5f84f3d3e824f3bd99a  compilation of exclusive mode ubershaders happens regardless of settings applied. EVEN with ubershaders off and unchecked "Compile Shaders on Startup" option.

**Comment by davidbepo** [comment]
this also happens to me

**Comment by Tinob** [comment]
this should be fixed in the latest version

**Comment by davidbepo** [comment]
verified fixed
